[package]
name = "ru_test1"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
endbasic-core = "0.11"
endbasic-std = "0.11"
futures-lite = "2.6"
tokio = { version = "1", features = ["full"] }

